name: pomo_server
description: Server for pomo app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  lucore:
    git:
      url: https://github.com/fuzzknob/lunart.git
      ref: main
      path: libs/lunart_core
  luex:
    git:
      url: https://github.com/fuzzknob/lunart.git
      ref: main
      path: libs/lunart_express
  dotenv: ^4.2.0
  cli_util: ^0.4.2
  acanthis: ^1.1.0
  uuid: ^4.5.1
  dartx: ^1.2.0

dev_dependencies:
  lints: ^5.1.1
