name: pomo_mobile
description: "Focusofi mobile app"
publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  hive_flutter: ^1.1.0
  gap: ^3.0.1
  flutter_form_builder: ^10.0.0
  form_builder_validators: ^11.1.2
  freezed: ^3.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  keep_screen_on: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: Jersery15
      fonts:
        - asset: assets/fonts/Jersey15-Regular.ttf
